name: xbr_gaode_navi_amap
description: include amap,search,location,navi
version: 1.0.0
homepage: https://gitee.com/mywentop

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.1
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.yilin.xbr.xbr_gaode_navi_amap
        pluginClass: XbrGaodeNaviAmapPlugin
      ios:
        pluginClass: XbrGaodeNaviAmapPlugin
